### ISSUE TITLE
"Creating default config file" not respecting configure prefix?

### ISSUE THREAD

**Issue by MikeLund** [DE-IBH/apt-dater#122]
Hi, maybe I am doing something wrong, but apt-dater is creating default configs outside of my prefix configuration for some reason. (But it still seems to be using my --prefix config files properly.)

> *\* Message: Creating default config file /Users/username/.config/apt-dater/apt-dater.xml
> *\* Message: Creating default config file /Users/username/.config/apt-dater/hosts.xml
> *\* Message: Creating default config file /Users/username/.config/apt-dater/screenrc

So my issue is, why are these default configs being made in my home directory, and how can I stop them? Thanks!

**Comment by liske** [comment]
This is intentional. The prefix tells where to install the global files but *apt-dater* will always parse the config files from the user's home directory. The default configuration in the user's home directory includes the global config files.

This make *apt-dater* usable in different deployment schemes:
- private user configs: just remove the include of the global configs from your `.config/apt-dater/` files
- multi user setup: put everything in `/etc/apt-dater`
- hybrid: combine both
