### ISSUE TITLE
needs permission to write /var/lib/apt-dater and /var/cache/apt-dater

### ISSUE THREAD

**Issue by tpo** [DE-IBH/apt-dater#78]
I'm using apt-dater as a plain user. When I run apt-dater though, it tries to write to /var/lib/apt-dater and /var/cache/apt-dater.

In order to be able to run apt-dater I've created those and chown'ed them to my user. However I think that is not "right".

If I'd run apt-dater as root, then /var would be the correct place to save state or cache, but as a simple user I think the correct place to save these would be ~/.cache or ~/.config

Many thanks for apt-dater!
*t

**Comment by liske** [comment]
Hi,

using paths within _/var/*/apt-dater/_ is intentional. Since you are building apt-dater from scratch you don't have the package magic which would create the directories at _/var/*/apt-dater/_ with special owner and mode settings (to enable multi-user support).

To use a single user setup you could set the paths to somewhere else (apt-dater.xml):
```xml
    <!--
        Path to hosts file and status directory.

    <paths
        hosts-file="path-to/hosts.xml"
        history-dir="path-to/history/"
        stats-dir="path-to/stats"/>
    -->
```

HTH,
Thomas

**Comment by tpo** [comment]
Thanks a lot Thomas!

It'd be nice to have these things ("single user mode", config options...) documented - I'll pick that task up next after I've finished my cloning machine... 

Thanks a lot really!
